sudo: required
language: go
addons:
  apt:
    packages:
    - rpm
    - snapd
go:
- 1.12.x
install:
- sudo snap install snapcraft --classic
script:
- make build
- make testacc
branches:
  only:
  - master
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
env:
  global:
  - PATH=/snap/bin:$PATH
  - secure: mk3RDW2TznOlPOtgAJP3cexpSJ92TZgJDccYylqmloGMjaFpbdJb2nbqFl1hPFjUSD1p51z0BlOuhxkh9eWSVychVOfYWtjz5wtZuo43vjKi84Yz4QuUIRyTBpCp7V1iSozxzO/ioiB8+5+j8DRaqtLuM27NtDDqutBl/ITkZx3odrzHBMC4zGSUBr8obvyNoA4NCLOrPA3NA/NstSU3bq+Rz/7kUmRxnK8+h/HNk73bBHzDzwt5c6Qp+VMjI57LfmG52cp82fZ2TRl/LGfMEBn8m4AV5wF7n9enyUWEm7vGRIIN9J4IsxIsRx4OL0RTeiavMiBkhf8Nti5d5KblRtjTTp2wja51fflKehqxZnbN5XueEPyezvPbfwASXgFrUcBoMhmfQk3OBPQF55w/lcg9rXn7hAScyCAbumt2Wk7dTfWklvC4kK3jj5Sd6VV1QluCFR7ahyCCXLHa6U/CknwCzhEwDnUirweq6ZIy3mLnJ7nsNCupNhWxos3OrS11mDKBALBSfErs/0puM5ziBBxpZ/Lb4wInwKNbghr2DHUKkHReJC1s8gXmyrZ0Pk1sNAkL+P7DyPHyWW8VdYhJ+/U7PDTwtYlIftbhWWLbEexUvnv2AVKpIej8VkXGPJskRBLffnu17bK4/ZGt1KSYSIkCyiur6TL1sYGMVFrz2Os=
