# This GitHub action can publish assets for release when a tag is created.
# Currently its setup to run on any tag that matches the pattern "v*" (ie. v0.1.0).
#
# This uses an action (paultyng/ghaction-import-gpg) that assumes you set your 
# private key in the `GPG_PRIVATE_KEY` secret and passphrase in the `PASSPHRASE`
# secret. If you would rather own your own GPG handling, please fork this action
# or use an alternative one for key handling.
#
# You will need to pass the `--batch` flag to `gpg` in your signing step 
# in `goreleaser` to indicate this is being used in a non-interactive mode.
#
name: docs-gen
on:
  push:
    branches:
    - docs-gen
# on:
#   push:
#     tags:
#       - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0' # The Go version to download (if necessary) and use.
      # -
      #   name: Import GPG key
      #   id: import_gpg
      #   uses: paultyng/ghaction-import-gpg@v2.1.0
      #   env:
      #     GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      #     PASSPHRASE: ${{ secrets.PASSPHRASE }}

      # - name: Install dependencies
      #     run: go mod vendor
       # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go env
        go get github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs
        ls -l
        go generate
    - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'docs'

        # The name of the user that will be displayed as the author of the commit
        # Default: author of the commit that triggered the run
        author_name: Aashwin Varshney

        # The email of the user that will be displayed as the author of the commit
        # Default: author of the commit that triggered the run
        author_email: aashwin.varshney@gmail.com

        # Name of the branch to use, if different from the one that triggered the workflow
        # Default: the branch that triggered the run
        branch: docs-gen

        # The local path to the directory where your repository is located. You should use actions/checkout first to set it up
        # Default: '.'
        # cwd: './path/to/the/repo'

        # The message for the commit
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: 'dont skip'

        # The flag used on the pull strategy
        # Default: '--no-rebase'
        # pull_strategy: '--no-rebase or --no-ff or --rebase'

        # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
        # Default: true
        # push: false

        # The arguments for the `git rm` command (see the paragraph below for more info)
        # Default: ''
        # remove: './dir/old_file.js'

        # Whether to use the --signoff option on `git commit` (only `true` and `false` are accepted)
        # Default: false
        # signoff: true

        # Arguments for the git tag command (the tag name always needs to be the first word not preceded by an hyphen)
        # Default: ''
        # tag: 'v1.0.0 --force'
      # - id: bump
      - name: Increment version
        uses: zwaldowski/match-label-action@v1
        with:
          allowed: major,minor,patch
      - uses: zwaldowski/semver-release-action@v1
        with:
          bump: ${{ steps.bump.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}