# This GitHub action can publish assets for release when a tag is created.
# Currently its setup to run on any tag that matches the pattern "v*" (ie. v0.1.0).
#
# This uses an action (paultyng/ghaction-import-gpg) that assumes you set your 
# private key in the `GPG_PRIVATE_KEY` secret and passphrase in the `PASSPHRASE`
# secret. If you would rather own your own GPG handling, please fork this action
# or use an alternative one for key handling.
#
# You will need to pass the `--batch` flag to `gpg` in your signing step 
# in `goreleaser` to indicate this is being used in a non-interactive mode.
#
name: docs-gen
on:
  push:
    branches:
    - docs-gen
# on:
#   push:
#     tags:
#       - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0' # The Go version to download (if necessary) and use.
      # -
      #   name: Import GPG key
      #   id: import_gpg
      #   uses: paultyng/ghaction-import-gpg@v2.1.0
      #   env:
      #     GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      #     PASSPHRASE: ${{ secrets.PASSPHRASE }}

      # - name: Install dependencies
      #     run: go mod vendor
       # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go env
        go mod vendor