# This github action bump creates a tag which acts as the semantic versioning of the repo
# It will use the label created on the pull request to determine which category should be 
# Increased.

# The PR must have one of these 3 labels for this workflow to run successfully.
# major, minor, patch
name: Bump version
on:
  push:
    branches:
      - github-actions-versioning
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        DRY_RUN: true